### PR TITLE
Feature/images

### PR DESCRIPTION
**Pull request by rossdylan**
Woo This is finally at a point I'm happy with. We now have a way to read in an image and print it out as xterm color codes in the terminal. It doesn't do any optimizations yet but it does the basic job of output images well.

### CODE REVIEW

**Comment by msoucy** [comment]
Issues:
- Tupfile needs to be updated to handle ImageMagick.
- Shouldn't the Makefile install the `.a` as well as the `.o`? While you're at it, use the `install` tool, which is meant for this task.
- Speaking of, preprocessor flags (`-I` mainly) should be put in `CPPFLAGS` not `CFLAGS`...and use implicit rules, that's what they're there for.
- `.PHONY: shared` isn't the name of the library nowadays...
- Still need to add the test program to the makefile, or even possibly split it into smaller test programs.
- is `xcolor_image_t` meant to have publicly accessible members?
- Use a test image

**Comment by rossdylan** [comment]
I agree with the following:
- Tupfile support for images
- `xcolor_image_t`things

The rest off these issues can be made into proper issues and fixed after feature/images is mainlined

**Comment by msoucy** [comment]
And the test image.

Splitting the others out into their own issues now.

**Comment by rossdylan** [comment]
Since most of these issues are just cleanups I'm going to go ahead and merge this in, and then work on finding a test image, and the others.

**Pull request merged**
