### PR TITLE
fab: Escape size is an optimizable constant

### PR DESCRIPTION
**Pull request by WillDignazio**
The escape length for the string can be derived with sizeof,
which is evaluate in the preprocessor.

fab: Error handling, off-by-one for prec_strlen

The macro prec_len includes the null terminator, remove the
offset. Add some error paths, and handle some possible logic
failures.

### CODE REVIEW

**Comment by rossdylan** [comment]
When compiling with clang it spits out 2 warnings

```
src/fab.c:220:6: warning: default label in switch which covers all enumeration values [-Wcovered-switch-default]
     default:
     ^
src/fab.c:221:6: warning: will never be executed [-Wunreachable-code]
     fprintf(stderr, "Invalid color code.\n");
     ^~~~~~~
```

I discussed it with @eatnumber1 and @crawford and @eatnumber1 brought up the fact that casting a number to an enum that isn't a valid enum is undefined behavior. Which means the compiler can do whatever it wants for the default case. The rest of the pull lgtm, so if the default case is removed I'll merge it in.

**Comment by WillDignazio** [comment]
That may be the case, but regardless, the default statement will catch invalid enumerations that may have been assigned, that's the point of it. I will remove it for the pull, but now you're relying on the compiler to catch those errors.

**Comment by crawford** [comment]
If the compiler believes it has every case covered (as it does it this case) it's free to omit the default case. Before you cast the integer into the enum, you need to ensure that it is valid. Otherwise, you are relying on undefined behavior.

**Comment by WillDignazio** [comment]
However in practice, clang/gcc will _not_ catch integer values assigned outside the enumeration's range of valid values. Take for example:

This program can be compiled cleanly with (the same flags as library):
clang -o test ./test.c -std=c99 -Wall -Wextra -pedantic -L. -lfab -Iinclude/
gcc -o test ./test.c -std=c99 -Wall -Wextra -pedantic -L. -lfab -Iinclude/

```
//test.c
#include <stdio.h>
#include "include/fab.h"

int
main(int argc, char *argv[])
{
        Color c;
        char* line;

        (void)argc;
        (void)argv;

        c = 100;
        line = "Colored Line";
        apply_color(c, line);

        return 0;
}
```

When run with my patches, it will catch the invalid value:

```
will@Marvin:~/Source/libfab$ ./test
Invalid color code.
```

But this isn't just a fluke to the architecture, and the compiler I used. The assignment of an enum to outside the enum range may be undefined, but as shown above this will slip by without any warning/errors.

Fortunately, as per the C99/C11 standard, the switch statement will perform an integer promotion to the controlling expression, which is 'c' in this case [see 6.8.4.2, 5]. So if execution reaches the switch statement, it will use the (most likely) invalid enumeration value as an integer, and catch it with the default case.

The intent of the default: is to catch logic errors, and provide a simple safety mechanism to avoid a segfault, which would occur otherwise.

**Comment by crawford** [comment]
I'll let @eatnumber1 respond to the "In practice" comment.
The proper way to handle this is to verify that the integer can be cast to the enum before you cast it. Then from that point forward, you can assume its valid (because it is). You'd want all of your input sanitization code in one place anyway; not strewn about your code base.

**Comment by eatnumber1** [comment]
To respond to one of your comments directly, you said:

> But this isn't just a fluke to the architecture, and the compiler I used. The assignment of an enum to outside the enum range may be undefined, but as shown above this will slip by without any warning/errors.

This is nonsense. You can't say that "I showed this above, so it's not specific to the architecture and compiler that I used to show this above." Also, since some undefined behavior is _provably impossible_ to determine at compile-time, it will never be a valid argument to say that behavior is permissible if no compiler errors or warnings occur.

Even if the compiler behaves this way today, that can change at any time, for any reason. Some cases the behavior might change includes:
- Switching to a different platform / architecture, thereby creating a portability problem.
- Updating your compiler / switching to a different compiler.
- Changing unrelated code. If the compiler didn't see an opportunity for optimization here, it's still possible that changing neighboring code might enable the compiler to see an opportunity.

An example of something that could have occurred:

> Your enum is represented as a char (allowed by the standard in [§6.7.2.2 subsection 4](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf)). Your integer value is 257. Casting your integer value to the enum type clamps it to 1, which is now a valid enum value. Your switch then promotes the char 1 to an int 1, and doesn't detect the error. This can quickly become an integer overflow attack.

Another

> The compiler emits a jump table for your switch statement which contains values for every defined value of your enum. Your int value, cast to the enum type is larger than the largest enum value, and the arithmetic used to calculate the position in the jump table results in jumping to an address which is off the end of the jump table.

Even though the switch will promote the integer value to an int, because of the original type of the value, it can statically determine the range of possible values of that int and optimize based on that.

For these reasons, and others, it's actually irrelevant what the observed behavior of one specific implementation, platform, architecture triple is. Undefined behavior is undefined. You can get the same behavior using well-defined methods. Do it that way instead. Here's an example of how:

``` c
enum E {
  FOO,
  BAR,
  E_LAST
  // Do not skip values in this enum.
};

int main() {
  int input = 1024;
  if (input >= E_LAST || input < 0) {
    // Invalid input
  }
  switch ((enum E) input) {
    case FOO:
    case BAR:
      break;
    case E_LAST:
      assert(false);
  }
}
```

All that said, it's actually somewhat ambiguous as to whether this is undefined. An excerpt from a discussion on ##c@freenode:

```
[11:36:12]  <eatnumber1>     Is casting a char whose value is outside the defined range for an enum to that enum UB like I suspect it is? If so, does someone have references into the standard showing that? I can't find it.
[11:36:48]  <naptime>    eatnumber1: It isn't UB to cast it, but it's UB to _use_ it in its casted form.  I'll find it, hang on.
[11:36:56]  <eatnumber1>     thanks
[11:38:10]  <naptime>    eatnumber1: Actually it might not be UB at all if it's a char specifically...
[11:38:53]  <edk>    it could ne
[11:39:07]  <edk>    be, too
[11:39:57]  <eatnumber1>     to give a little more context, I'm discussing with some friends whether a compiler compiling a switch statement that covers all the values of an enum _and_ has a default case is allowed to remove the default case
[11:40:41]  <eatnumber1>     and if using a variable with enum type whose value is outside the defined range for that enum type is UB, then the compiler would be allowed to
[11:40:54]  <naptime>    "Each enumerated type shall be compatible with char, a signed integer type, or an unsigned integer type.  The choice of type is implementation-defined,..."
[11:41:20]  <edk>    if by "defined range" you mean only the enumerated values in that enum type, no, it's not UB
[11:41:29]  <naptime>    So if your char value is in the range 0 to +127 then you can cast it, but otherwise it's implementation-defined.
[11:42:51]  <eatnumber1>     it's defined by that sentence you posted above? I thought that only restricts the storage
[11:44:33]  <naptime>    eatnumber1: You know what, I think you're right about it being UB.
[11:45:18]  <naptime>    Same page 118: "The enumerated type is incomplete until immediately after the } that terminates the list of enumerator declarations, and complete thereafter."
[11:46:14]  <naptime>    Perhaps the "complete thereafter" implies that no new values can be added, even by a cast.
[11:46:55]  <eatnumber1>     the standard seems somewhat ambiguous on this
```

But it's only ambiguous if you are coming from a variable whose value is in the defined `char` range, which is 0 to 127. Otherwise, as stated above, it's either undefined or implementation defined.

**Comment by WillDignazio** [comment]
> This is nonsense. You can't say that "I showed this above, so it's not specific to the architecture and compiler that I used to show this above." Also, since some undefined behavior is provably impossible to determine at compile-time, it will never be a valid argument to say that behavior is permissible if no compiler errors or warnings occur.

The intention wasn't to state or insinuate that you could expect that behavior to be reliable, just that at this time, you _can_ do it, and you will get a segfault. That is, you can do it as someone writing an application with this api.

> The compiler emits a jump table for your switch statement which contains values for every defined value of your enum. Your int value, cast to the enum type is larger than the largest enum value, and the arithmetic used to calculate the position in the jump table results in jumping to an address which is off the end of the jump table.

This is perhaps the most damning to my argument. Though my understanding at the time was that while the cast from a value larger than the enum was undefined behaviour, the usage after was not. The storage class of the enum is known and assigned to some value. The default: uses the promoted integer value observe that it's not within the switch values, and so on.

If that is not the case, then yeah, we might be playing pacman while switch-ing.

**Comment by rossdylan** [comment]
As per the request of @WillDignazio I'm closing this so he can fix up the changes and resubmit.

**Pull request closed without merging**
